# site setting
title: gogotr's devlog
name: gogotr's blog
markdown: kramdown
pygments: true

# google analytics
google_analytics_id: UA-123259882-1

# Disqus
disqus_url : http://disqus.com/by/disqus_S70ebkx8Gy
disqus_id : disqus_S70ebkx8Gy


#font
# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:        "'Roboto Slab', 'Nanum Gothic', Helvetica, Arial, sans-serif"

# The text font. Expects a string that is a valid CSS font-family value.
font:                "'Noto Sans', 'Nanum Gothic', Helvetica, Arial, sans-serif"

# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts:        Roboto+Slab:700|Noto+Sans:400,400i,700,700i
